fields:
- type: list
  caption: Topology
  name: topology
  value: standalone
  values:
    - value: standalone
      caption: Standalone
      tooltip: <h3 style='margin:5px; text-align:center'>Optimized Elastic Container</h3><div style='text-align:center'>For dev, test and small production sites</div><img width='300' height='200' style='margin:15px 0; margin-left:-10px' src='https://raw.githubusercontent.com/sych74/wordpress-master/master/images/standalone.svg?sanitize=true'>
    - value: cluster
      caption: HA Cluster
      tooltip: <h3 style='margin:5px; text-align:center'>High Availability and Performance</h3><div style='text-align:center'>For medium and large size production sites</div><img width='270' height='360' style='margin:0 0;' src='https://raw.githubusercontent.com/sych74/wordpress-master/master/images/cluster.svg?sanitize=true'>
  tipParams:
    dismissDelay: 600000
    anchor: l
    hideOnOver: false
    showDelay: 0

- caption: Regions
  type: regionlist
  name: regions
  disableInactive: true
  selectFirstAvailable: true
  multiSelect: true
  min: 1
  max: 2
  filter:
    isActive: true
  default: premium-vz7

- caption: Env Name
  type: envname
  name: envName
  dependsOn: region
  randomName: true
  showFullDomain: false
  required: true

- name: wp_title
  caption: WP Title
  type: string
  inputType: hidden
  default: HelloWorld
  required: 'true'
  regex: "^[\\w-.]*$"
  regexText: Incorrect WP Title.

- caption: Addons
  type: displayfield
  name: displayfield
  markup:

- type: checkbox
  name: le-addon
  caption: Install Let's Encrypt SSL with Auto-Renewal
  value: true
